#!/bin/bash

TARGET_FILE="$HOME/.config/hypr/hyprsource/monitors.conf"

notify-send -i "display" "WARNING" "Toggle primary display?" \
  --action="yes=Enable" \
  --action="no=Disable" \
  | while read -r action; do
    case "$action" in
      yes)
        sed -i 's/eDP-1, disable/eDP-1/g' $TARGET_FILE
        shimejictl config set "MASCOT_SCALE" 0.75
        ;;
      no)
        sed -i 's/eDP-1/eDP-1, disable/g' $TARGET_FILE
        shimejictl config set "MASCOT_SCALE" 1.25
        ;;
    esac
  done
