#!/bin/bash

notify-send -i "display" "Display Management" "You sure abt dis?" \
    --action="extend=Extend" \
    --action="auto=Auto" \
    --action="mirror=Mirror" \
    | while read -r action; do
        case "$action" in
            extend)
                display-daemon extend
                ;;
            mirror)
                display-daemon mirror 
                ;;
            auto)
                display-daemon
                ;;
        esac
    done
